has_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    # userauths url
    path("user/" ,include("userauths.urls")),
    path("", include("hotel.urls")),
    path("booking/", include("booking.urls")),

    #ckeditor-5
    path("ckeditor-5/", include("django_ckeditor_5.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.urls import path
from hotel import views

app_name="hotel"

urlpatterns=[
    path("", views.index, name="index"),
    path("detail/<slug>/", views.hotel_detail, name="hotel_detail"),
    path("detail/<slug:slug>/room-type/<slug:rt_slug>/", views.room_type_detail, name="room_type_detail"),
    path("selected_rooms/", views.selected_rooms, name="selected_rooms"),
    path("checkout/<booking_id>/", views.checkout, name="checkout"),

]

hotel/models.py
from django.db import models
from userauths.models import User
from shortuuid.django_fields import ShortUUIDField
import shortuuid
from django.utils.text import slugify
from django.utils.html import mark_safe
from django_ckeditor_5.fields import CKEditor5Field
from taggit.managers import TaggableManager

HOTEL_STATUS=(
    ("Draft","Draft"),
    ("Disabled","Disabled"),
    ("Rejected","Rejected"),
    ("In Review","In Review"),
    ("Live","Live"),
)

ICON_TYPE=(
    ("Bootstrap Icons","Bootstrap Icons"),
    ("fontawesome Icons","fontawesome Icons"),
    ("Box Icons","Box Icons"),
    ("Remi Icons","Remi Icons"),
    ("Flat Icons","Flat Icons"),
)

PAYMENT_STATUS=(
    ("paid","paid"),
    ("pending","pending"),
    ("processing","processing"),
    ("cancelled","cancelled"),
    ("initiated","initiated"),
    ("failed","failed"),
    ("refunding","refunding"),
    ("refunded","refunded"),
    ("unpaid","unpaid"),
    ("expired","expired"),
)


class Hotel(models.Model):
    user=models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name=models.CharField(max_length=100, default="Daniel")
    description=CKEditor5Field(null=True, blank=True, config_name="extends")
    image=models.FileField(upload_to="hotel_gallery", default="static/img/about-1.jpg")
    address=models.CharField(max_length=200 , default="111, 30108 Nairobi Kenya")
    mobile=models.CharField(max_length=200, default="0742580239")
    email=models.EmailField(max_length=100, default="ngumodaniel80@gmail.com")
    status=models.CharField(max_length=20, choices=HOTEL_STATUS, default="Live")

    tags=TaggableManager( blank=True)
    views=models.IntegerField(default=0), 
    featured=models.BooleanField(default=False)
    hid=ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefjhijklmnopqrstuvwxyz")
    slug=models.SlugField(unique=True)
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if self.slug == "" or self.slug == None:
            uuid_key=shortuuid.uuid()
            uniqueid=uuid_key[:4]
            self.slug=slugify(self.name) + '-' + str(uniqueid.lower())

        super(Hotel, self).save(*args, **kwargs)

    def thumbnail(self):
        return mark_safe("<img src='%s' width='50' height='50' style='object-fit:cover; border-radius:6px;'/>" %(self.image.url)) 
    
    def hotel_gallery(self):
        return HotelGallery.objects.filter(hotel=self)

    def hotel_room_types(self):
        return RoomType.objects.filter(hotel=self)
    
class HotelGallery(models.Model):
    hotel=models.ForeignKey(Hotel, on_delete=models.CASCADE)
    image=models.FileField(upload_to="hotel_gallery", default="static/img/about-1.jpg")
    hgid=ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefjhijklmnopqrstuvwxyz")

    def __str__(self):
        return str(self.hotel.name)
    
    class Meta:
        verbose_name_plural="Hotel Gallery"


class HotelFeatures(models.Model):
    hotel=models.ForeignKey(Hotel, on_delete=models.CASCADE)
    icon_type=models.CharField(max_length=100, null=True, blank=True, choices=ICON_TYPE)
    icon=models.CharField(max_length=100, null=True, blank=True)
    name=models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.name)
    
    class Meta:
        verbose_name_plural="Hotel Features"

class HotelFaqs(models.Model):
    hotel=models.ForeignKey(Hotel, on_delete=models.CASCADE)
    question=models.CharField(max_length=1000)
    answer=models.CharField(max_length=1000,null=True, blank=True)
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.question)
    
    class Meta:
        verbose_name_plural="Hotel FAQs"

class RoomType(models.Model):
    hotel=models.ForeignKey(Hotel, on_delete=models.CASCADE)
    type=models.CharField(max_length=10)
    price=models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    number_of_beds=models.PositiveIntegerField(default=0)
    room_capacity=models.PositiveIntegerField(default=0)
    rtid=ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefjhijklmnopqrstuvwxyz")
    slug=models.SlugField(unique=True)
    date=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.type}-{self.hotel.name}-{self.price}"
    
    class Meta:
        verbose_name_plural="Room Type"

    def room_count(self):
        Room.objects.filter(room_type=self).count()

    def save(self, *args, **kwargs):
        if self.slug == "" or self.slug == None:
            uuid_key=shortuuid.uuid()
            uniqueid=uuid_key[:4]
            self.slug=slugify(self.name) + '-' + str(uniqueid.lower())

        super(RoomType, self).save(*args, **kwargs)

class Room(models.Model):
    hotel=models.ForeignKey(Hotel, on_delete=models.CASCADE)
    room_type=models.ForeignKey(RoomType, on_delete=models.CASCADE)
    room_number=models.CharField(max_length=1000)
    is_available=models.BooleanField(default=True)
    rid=ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefjhijklmnopqrstuvwxyz")
    date=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.room_type.type}-{self.hotel.name}"
    
    class Meta:
        verbose_name_plural="Rooms"

    def price(self):
        return self.room_type.price

    def number_of_beds(self):
        return self.room_type.number_of_beds
    
class Booking(models.Model):
    user=models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    payment_status=models.CharField(max_length=100, choices=PAYMENT_STATUS)
    full_name=models.CharField(max_length=200)
    email=models.EmailField(max_length=100,default="ngumodaniel80@gmail.com")
    phone=models.CharField(max_length=200)

    hotel=models.ForeignKey(Hotel, on_delete=models.SET_NULL, null=True, blank=True)
    room_type=models.ForeignKey(RoomType, on_delete=models.SET_NULL, null=True, blank=True)
    room=models.ManyToManyField(Room)
    before_discount=models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    total=models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    saved=models.DecimalField(max_digits=12, decimal_places=2, default=0.00)

    check_in_date=models.DateField()
    check_out_date=models.DateField()

    total_days=models.PositiveIntegerField(default=0)
    num_adults=models.PositiveIntegerField(default=1)
    num_children=models.PositiveIntegerField(default=0)

    checked_in=models.BooleanField(default=False)
    checked_out=models.BooleanField(default=False)

    is_active=models.BooleanField(default=False)

    checked_in_tracker=models.BooleanField(default=False)
    checked_out_tracker=models.BooleanField(default=False)

    date=models.DateTimeField(auto_now_add=True)
    stripe_payment_intent=models.CharField(max_length=1000, null=True, blank=True)
    success_id=models.CharField(max_length=1000, null=True, blank=True)
    booking_id=ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefjhijklmnopqrstuvwxyz")

    def __str__(self):
        return f"{self.booking_id}"

    def rooms(self):
        return self.room.all().count()
    
class ActivityLog(models.Model):
    booking=models.ForeignKey(Booking,on_delete=models.CASCADE)
    guest_out=models.DateTimeField()
    guest_in=models.DateTimeField()

    description=CKEditor5Field(null=True, blank=True, config_name="extends")
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.booking}"
    
class StaffOnDuty(models.Model):
    booking=models.ForeignKey(Booking,on_delete=models.CASCADE)
    staff_id=models.CharField(max_length=100, null=True, blank=True)
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.staff_id}"












    






















    






 

hotel/views.py
from django.shortcuts import render, redirect
from hotel.models import Hotel, Booking, ActivityLog, StaffOnDuty,Room, RoomType,HotelGallery, HotelFaqs, HotelFeatures
from django.contrib import messages
from datetime import datetime

def index(request):
    hotels=Hotel.objects.filter(status="Live")
    context={
        "hotels":hotels
    }
    return render(request, "hotel/hotel.html", context)

def hotel_detail(request, slug):
    hotel=Hotel.objects.get(status="Live", slug=slug)

    context={
        "hotel":hotel
    }
    return render(request, "hotel/hotel_detail.html", context)

def room_type_detail(request, slug, rt_slug):
    hotel=Hotel.objects.get(status="Live", slug=slug)
    room_type=RoomType.objects.get(hotel=hotel, slug=rt_slug)
    rooms=Room.objects.filter(room_type=room_type, is_available=True)

    id=request.GET.get("hotel-id")
    checkin=request.GET.get("checkin")
    checkout=request.GET.get("checkout")
    adult=request.GET.get("adult")
    children=request.GET.get("children")


    context={
        "hotel":hotel,
        "room_type":room_type,
        "rooms":rooms,
        "id":id,
        "checkin":checkin,
        "checkout":checkout,
        "adult":adult,
        "children":children,
        
    }
    return render(request, "hotel/room_type_detail.html", context)

def selected_rooms(request):
    total=0
    room_count=0
    total_days=0
    adult=0
    children=0
    checkin=""
    checkout=""


    if 'selection_data_obj' in request.session:


        if request.method=="POST":
            for h_id, item in request.session['selection_data_obj'].items():
                id=int(item['hotel_id'])
                checkin=(item['checkin'])
                checkout=(item['checkout'])
                adult=int(item['adult'])
                children=int(item['children'])
                room_type_=int(item['room_type'])
                room_id=int(item['room_id'])
                hotel=Hotel.objects.get(id=id)
                room=Room.objects.get(id=room_id)
                user=Hotel.objects.get(id=id)
                room_type=RoomType.objects.get(id=room_type_)

        date_format="%Y-%m-%d"

        checkin_date=datetime.strptime(checkin, date_format)
        checkout_date=datetime.strptime(checkout, date_format)
        time_difference=checkout_date-checkin_date
        total_days=time_difference.days
        full_name=request.POST.get('full_name')
        email=request.POST.get('email')
        phone=request.POST.get('phone')

        booking=Booking.objects.create(
            hotel=hotel,
            room_type=room_type,
            checkin_date=checkin,
            checkout_date=checkout,
            total_days=total_days,
            num_adults=adult,
            num_children=children,
            full_name=full_name,
            email=email,
            phone=phone,
            user=request.user or None
        )

        # if request.user.is_authenticated:
        #     booking.user=request.user
        #     booking.save()
        # else:
        #     booking.user==None
        #     booking.save()

        for h_id, item in request.session['selection_data_obj'].items():
            room_id=int(item["room_id"])
            room=Room.objects.get(id=room_id)
            booking.room.add(room)

            room_count += 1
            days=total_days
            price=room_type.price

            room_price=price * room_count
            total=room_price* days

        booking.total += float(total)
        booking.before_discount += float(total)

        booking.save()
        messages.success(request, "Check out")
        return redirect("hotel:checkout", booking.booking_id)

       




        hotel=None
        for h_id, item in request.session['selection_data_obj'].items():
         id=int(item['hotel_id'])
         checkin=(item['checkin'])
         checkout=(item['checkout'])
         adult=int(item['adult'])
         children=int(item['children'])
         room_type_=int(item['room_type'])
         room_id=int(item['room_id'])

         room_type=RoomType.objects.get(id=room_type)

         date_format="%Y-%m-%d"

         checkin_date=datetime.strptime(checkin, date_format)
         checkout_date=datetime.strptime(checkout, date_format)

         time_difference=checkout_date-checkin_date
         total_days=time_difference.days

         room_count += 1
         days=total_days
         price=room_type.price

         room_price=price * room_count
         total=room_price* days

         hotel=Hotel.objects.get(id=id)

         context={
             "data":request.session['selection_data_obj'],
             "total_selected_items":len(request.session['total_selected_items']),
             "total":total,
             "total_days":total_days,
             "adult":adult,
             "children":children,
             "checkin":checkin,
             "checkout":checkout,
             "hotel":hotel,

         }
         return render(request, "hotel/selected_rooms.html", context)


    else:
        messages.warning(request,"no selected rooms yet")
        return redirect("/")
    
    return render(request, "hotel/selected_rooms.html")


def checkout(request, booking_id):
    booking=Booking.objects.get(booking_id=booking_id)

    context={
        "booking":booking
    }

    return render(request, "hotel:checkout.html", context)

templates/hotel/checkout.html
{{booking}}

templates/hotel/selected_rooms.html
{% extends 'partials/base.html' %}
{% load static %}


{% block content %}
        <!-- Page Header Start -->
        <div class="container-fluid page-header mb-5 p-0" style="background-image: url(img/carousel-1.jpg);">
            <div class="container-fluid page-header-inner py-5">
                <div class="container text-center pb-5">
                    <h1 class="display-3 text-white mb-3 animated slideInDown">Booking</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center text-uppercase">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item"><a href="#">Pages</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">Booking</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        <!-- Page Header End -->


        <!-- Booking Start -->
        <div class="container-fluid booking pb-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container">
                <div class="bg-white shadow" style="padding: 35px;">
                    <div class="row g-2">
                        <div class="col-md-10">
                            <div class="row g-2">
                                <div class="col-md-3">
                                    <div class="date" id="date1" data-target-input="nearest">
                                        <input type="text" class="form-control datetimepicker-input"
                                            placeholder="Check in" data-target="#date1" data-toggle="datetimepicker" />
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="date" id="date2" data-target-input="nearest">
                                        <input type="text" class="form-control datetimepicker-input" placeholder="Check out" data-target="#date2" data-toggle="datetimepicker"/>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <select class="form-select">
                                        <option selected>Adult</option>
                                        <option value="1">Adult 1</option>
                                        <option value="2">Adult 2</option>
                                        <option value="3">Adult 3</option>
                                    </select>
                                </div>
                                <div class="col-md-3">
                                    <select class="form-select">
                                        <option selected>Child</option>
                                        <option value="1">Child 1</option>
                                        <option value="2">Child 2</option>
                                        <option value="3">Child 3</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <button class="btn btn-primary w-100">Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Booking End -->


        <!-- Booking Start -->
        <div class="container-xxl py-5">
            <div class="container">
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title text-center text-primary text-uppercase">Room Booking</h6>
                    <h1 class="mb-5">Book A <span class="text-primary text-uppercase">Luxury Room</span></h1>
                </div>
                <div class="row g-5">
                    <div class="col-lg-6">
                        <div class="row g-3">
                    <ul>
                        {% for id, item in data.items %}
                        <li>
                            <h5>
                                Room:{{item.room_name}}
                                <small>
                                <a href="" style="cursor: pointer;" class="delete-item"><i class="fas fa-transport"></i></a>
                            </small></h5>
                            <p><strong>Beds: {{item.number_of_beds}}</strong></p>
                            <span>{{item.room_price}}$</span>
                        </li>
                        {% endfor %}
                    </ul>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="wow fadeInUp" data-wow-delay="0.2s">
                            <form>
                                <div class="row g-3">
                                    <div class="col-md-6">

                                       
                                        <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                                            <div class="room-item shadow rounded overflow-hidden">
                                                <div class="position-relative">
                                                    <a href="{% url 'hotel:hotel_detail' hotel.slug %}"><img class="img-fluid"
                                                            src="{{hotel.image.url}}" alt=""></a>
                                                    <small
                                                        class="position-absolute start-0 top-100 translate-middle-y bg-primary text-white rounded py-1 px-3 ms-4">$100/Night</small>
                                                    {% if hotel.featured %}
                                                    <small
                                                        class="position-absolute start-0 top-150  bg-success text-white rounded py-1 px-3 ms-4">featured</small>
                                                    {% endif %}
                                                </div>
                                                <div class="p-4 mt-2">
                                                    <div class="d-flex justify-content-between mb-3">
                                                        <h5 class="mb-0">{{hotel.name}}</h5>
                                                        <div class="ps-2">
                                                            <small class="fa fa-star text-primary"></small>
                                                            <small class="fa fa-star text-primary"></small>
                                                            <small class="fa fa-star text-primary"></small>
                                                            <small class="fa fa-star text-primary"></small>
                                                            <small class="fa fa-star text-primary"></small>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex mb-3">
                                                        <small class="border-end me-3 pe-3"><i class="fa fa-bed text-primary me-2"></i>3
                                                            Bed</small>
                                                        <small class="border-end me-3 pe-3"><i class="fa fa-bath text-primary me-2"></i>2
                                                            Bath</small>
                                                        <small><i class="fa fa-wifi text-primary me-2"></i>Wifi</small>
                                                    </div>
                                                    <p class="text-body mb-3">{{hotel.address}}</p>
                                                    <p class="text-body mb-3">{{hotel.mobile}}, {{hotel.email}}</p>
                                                    <ul>
                                                        <li>Checkin <span>{{checkin}}</span></li>
                                                        <li>Checkout <span>{{checkout}}</span></li>
                                                        <li>Total Days <span>{{tota_days}}</span></li>
                                                        <li>adult <span>{{adult}}</span></li>
                                                        <li>children <span>{{children}}</span></li>
                                                        <li class="total-cost"> Total Cost <span>{{total}}$</span></li>
                                                    </ul>
                                                    <div class="d-flex justify-content-between">
                                                        <a class="btn btn-sm btn-primary rounded py-2 px-4" href="{% url 'hotel:hotel_detail' hotel.slug %}">View Detail</a>
                                                        <a class="btn btn-sm btn-dark rounded py-2 px-4" href="">Book Now</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    <div class="col-12">
                                        <button class="btn btn-primary w-100 py-3" type="submit">Book Now</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Booking End -->

        <!-- form -->
        <div class="col-lg-6">
            <div class="wow fadeInUp" data-wow-delay="0.2s">
                <form method="POST">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-md-6">
                            <div class="form-floating">
                                <input name="full_name" type="text" class="form-control" id="name" placeholder="Your Name">
                                <label for="name">Your Name</label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-floating">
                                <input name="email" type="email" class="form-control" id="email" placeholder="Your Email">
                                <label for="email">Your Email</label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-floating date" id="date3" data-target-input="nearest">
                                <input type="text" class="form-control datetimepicker-input" id="checkin" placeholder="Check In" data-target="#date3" data-toggle="datetimepicker" />
                                <label for="checkin">Check In</label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-floating date" id="date4" data-target-input="nearest">
                                <input type="text" class="form-control datetimepicker-input" id="checkout" placeholder="Check Out" data-target="#date4" data-toggle="datetimepicker" />
                                <label for="checkout">Check Out</label>
                            </div>
                        </div>

                        <div class="col-12">
                            <div class="form-floating">
                                <textarea class="form-control" placeholder="Special Request" id="message" style="height: 100px"></textarea>
                                <label for="message">Special Request</label>
                            </div>
                        </div>
                        <div class="col-12">
                            <button class="btn btn-primary w-100 py-3" type="submit">Book Now</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!-- endform  -->


        <!-- Newsletter Start -->
        <div class="container newsletter mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="row justify-content-center">
                <div class="col-lg-10 border rounded p-1">
                    <div class="border rounded text-center p-1">
                        <div class="bg-white rounded text-center p-5">
                            <h4 class="mb-4">Subscribe Our <span class="text-primary text-uppercase">Newsletter</span></h4>
                            <div class="position-relative mx-auto" style="max-width: 400px;">
                                <input class="form-control w-100 py-3 ps-4 pe-5" type="text" placeholder="Enter your email">
                                <button type="button" class="btn btn-primary py-2 px-3 position-absolute top-0 end-0 mt-2 me-2">Submit</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Newsletter Start -->
        
        {% endblock content %}